# Generated by Django 5.1 on 2024-12-01 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_remove_journey_rider_journey_riders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='riders',
            field=models.ManyToManyField(blank=True, null=True, related_name='riders_driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
